[book]
title = "NashmiC Documentation"
authors = ["Ziad Al Sharif"]
language = "en"
src = "src"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/Ziadstr/nashmic"
additional-css = ["theme/custom.css"]
additional-js = []
